name: Selenium Automation CI

on:
push:
branches: [ "main" ]

jobs:
selenium-tests:
runs-on: ubuntu-latest


steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Set up Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Setup Chrome
    uses: browser-actions/setup-chrome@v1

  - name: Install Dependencies
    run: mvn clean install -DskipTests

  - name: Run Tests (Headless Mode)
    run: mvn test -Denv=qa -Dbrowser.headless=true

  - name: Upload Reports
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: test-report
      path: |
        test-output/
        target/surefire-reports/
